## Ex1: Meeting the first Numpy Arrays

### Task 1: Import Numpy

In [3]:
# the code below is to import Numpy into my notebook

import numpy as np

# the code cell runs sucessfully without an error message, which indicates that Numpy has been successfully imported.

### Task 2: Creation of an Array

In [4]:
# the code below is to create an array from a python list.

# A python List
temperatures = [27.5,29,28.5]

# An Array
tem = np.array(temperatures)

print (tem)

[27.5 29.  28.5]


### Task 3: Inspect the Data Type

In [5]:
# the code below is to determine the data type of the array "tem" creatd above.

data_type = tem.dtype

print (data_type)

float64


### Task 4: Create a 2D Array

In [6]:
# the code below is create a 2D Array.

# A nested list
weather_data = [
    [27.5,28.0,29.5],
    [28.0,29.0,30.0]
]

# to convert the weather_data into a numpy array
weather_info = np.array(weather_data)

print (weather_info)

[[27.5 28.  29.5]
 [28.  29.  30. ]]


## Ex2: Python List Vs Numpy Arrays

### Task 1: Math operations with python List

In [7]:
# the code below is to perform a mathematical operation with python list and observe the result

# python list
sales_timothy = [10,15,20]
sales_brenda = [5,10,15]

result = sales_timothy + sales_brenda 
print (result)


# 1: the result did not produce [15,25,35]
# 2: the result gave a concantenation instead
# 3: A concatenated result of sales_timothy and sales_brenda was displayed instead because python list cannot python direct element-wise operation.

[10, 15, 20, 5, 10, 15]


### Task 2: Convert the Python list to Numpy Arrays

In [8]:
# the code below is to convert the python list stated above into numpy arrays

# python lists
sales_timothy
sales_brenda

# to numpy arrays
sales_T = np.array(sales_timothy)
sales_B = np.array(sales_brenda)

# to perform addition on both arrays above
Result = sales_T + sales_B
print (Result)

[15 25 35]


### Task 3: Compare the Results

In [9]:
# the code below is to compare the output of the results on the operation performed on the python list and numpy arrays

# Approach               Result
python_list =           [10,15,20,5,10,15]

numpy_array =           [15,25,35]

# Question: why is numpy useful

# Answer:
# Numpy is useful because its ability to perform independent operations on corresponding elements of its array makes...
# ... the execution time of its operations faster and much more efficient.

#### Challenge : Create and Perform operations on new Arrays

In [10]:
# the code below is to create new arrays and perform operations on them.

# first, python list
online_sales = [120,300,420,540,250]        #each sale record represent a sales record for each day of the week
store_sales = [200,300,340,450,230]         # from Monday to Friday.

# second, convert the python lists to numpy arrays
online_S = np.array(online_sales)
store_S = np.array(store_sales)

# to calculate the combine sales of the each day of the week by performing addition operation on the arrays
combine_sales = online_S + store_S
print ("Combined Sales Result",combine_sales)
print ('-' *50)

# the code below is to perform another operation that shows the difference between online_sales and store_sales
sales_difference = online_S - store_S
print ("Sales Difference",sales_difference)

Combined Sales Result [320 600 760 990 480]
--------------------------------------------------
Sales Difference [-80   0  80  90  20]


## Ex3 - Mini Project : Weather Data Quick Analysis

### Part 1: Create the Dataset

In [11]:
# the code below is to demonstrate the import of numpy.
import numpy as np

# the code below is to create the python list
# python list
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]

# the code below is to convert the list into a numpy array
temp = Temperature = np.array(temperatures)

# Task : Display the numPy Array
print (f"""Temperatures:{temp}
Data Type:{type (temp)}"""
      )

Temperatures:[27.5 29.  30.5 28.  31.  32.5 30. ]
Data Type:<class 'numpy.ndarray'>


### Part 2: Understand the Array and Answer Questions

In [12]:
# the codes below is to give answers to questions asked

# Question 1: is the Temperature array a 1D or 2D?
# Answer : the array is a 1D
print (temp)
print ('Temperature array is 1D')
print('-' * 50)

# Question 2: is the array a Vector or a Matrix?
# Answer: the  Array is a Vector
print (temp)
print ('The Array is a Vector')
print ('-' * 50)

# Question 3: what is the datatype of the Temp?
# Answer: from the operation above, the datatype of the Temp is : <class 'numpy.ndarray'>
print ("Data Type:", type (temp))
print ('-' * 50)

# Question 4: How many Temperature observations are present ?
# Answer: The Temperature observations are 7
print ("Temperature Observations:", len(temp))

[27.5 29.  30.5 28.  31.  32.5 30. ]
Temperature array is 1D
--------------------------------------------------
[27.5 29.  30.5 28.  31.  32.5 30. ]
The Array is a Vector
--------------------------------------------------
Data Type: <class 'numpy.ndarray'>
--------------------------------------------------
Temperature Observations: 7


### Part 3: Perform Numerical Operations

In [13]:
# the code below is create a numPy array representing the temperature targets.

# the python list
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]

# to convert to an Array
Target = np.array(target)


#### Task A: Temperature Difference

In [14]:
# the code below is to calculate the difference between the recorded temperature and the targeted temperature.

# recorded temperature
recorded_temp = temp

# targeted temperature
targeted_temp = Target

# to perform the operation
temp_difference = temp - Target
print ("Temperature Difference:", temp_difference)


Temperature Difference: [-0.5  1.   1.5  0.   1.   2.5  1. ]


#### Task B: Temperature Increase

In [15]:
# the code below is the demonstrate the resulting effect of increasing the temperatues by a multiple of 2.
# for this task, we will use the initial recorded temperature readings for the increase simulation.

# a variable for the temperature increase
increased_temperature = (temp * 2)

print ("Result of the Temperature Increase Simulation:", increased_temperature)
    


Result of the Temperature Increase Simulation: [55. 58. 61. 56. 62. 65. 60.]


### Part 4: Think Like an Analyst

#### Business 1: which day appears to have the highest recorded temperature?

In [16]:
# the code below is to answer business questions
days = ["monday", "tuesday","wedensday", "thursday","friday","saturday","sunday"]
temperatures
target
# Answer:
print (f"""Highest Tempearture Recorded:{max(temperatures)} degrees, was recorded on Day {(temperatures.index(max(temperatures)) + 1)}.
which is {days [5]}""")
# 1 is added to the index in order to get the accurate day since python index count starts from zero (0) instead of 1.


Highest Tempearture Recorded:32.5 degrees, was recorded on Day 6.
which is saturday


#### Business Question 2: on which day was the recorded temperature above the target temperature?

In [17]:
# the code below is the answer the business question above
# Answer:
for i in range (7):
    if temperatures[i] > target [i]:
        print ("Recorded Temperature was above the Target Temperature on:", days[i])

Recorded Temperature was above the Target Temperature on: tuesday
Recorded Temperature was above the Target Temperature on: wedensday
Recorded Temperature was above the Target Temperature on: friday
Recorded Temperature was above the Target Temperature on: saturday
Recorded Temperature was above the Target Temperature on: sunday


#### Business Question 3: what does the temperature difference tell the monitoring team?

In [18]:
# the code below is to answer the business question 3.
# Answer:
above = 0
below = 0
equal = 0

for i in range (7):
    if temperatures [i] > target [i]:
        above += 1

    elif temperatures [i] == target [i]:
        equal += 1

    else:
        below += 1

print (f"""
The Temperature difference tells the monitoring team that;
- the recorded temperatures was above the target temperatures on {above} different days.
- the recorded temperature was equal to the target temperature only on  {equal} day,
- the recorded temperature was below the target temperature only on {below} day as well.
""")


The Temperature difference tells the monitoring team that;
- the recorded temperatures was above the target temperatures on 5 different days.
- the recorded temperature was equal to the target temperature only on  1 day,
- the recorded temperature was below the target temperature only on 1 day as well.



#### Business Question 4: 
#### Why would using a NumPy array be more convenient than keeping the temperatures 
#### only as a Python list for these numerical operations?

### =================================================================
### Answer: 
##### Using a numPy array would be more convenient because of numPy-array's ability to perform independent operations
##### on its corresponding elements, thereby making the operation execution time faster and more efficient compared to keeping
##### the temperatures as only python list.

## EX4: MINI PROJECT CHALLENGE

##### Introduction

This project is focused on the Temperature records of a weather station.

Given a weather station has three locations:
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

Task is to create NumPy arrays for all three locations, and answer the business questions thay follows


In [32]:
# the code below is to demonstrate the import of NumPy into our notebook workspace for this purpose of the
# MINI PROJECT CHALLENGE

import numpy as np

# Note: if numpy has been succesfully imported, after running this cell/code, no error message would appear.
#       but if Numpy import wasn't successful, there would be an error message below this cell.

In [20]:
# the code below is to create weather records for three stations
# first we create the python list for each record

# python list
lagos = [27.5, 29.0, 30.5, 28.0, 31.0]
abuja = [25.0, 28.0, 29.5, 30.0, 32.0]
ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

# then we convert the python lists to numpy arrays
Lagos = np.array(lagos)
Abuja = np.array(abuja)
Ibadan = np.array(ibadan)

print (Lagos)
print (Abuja)
print (Ibadan)
# the subsequent codes below this cell are to answer business questions from the record of temperatures above.

[27.5 29.  30.5 28.  31. ]
[25.  28.  29.5 30.  32. ]
[26.5 28.5 29.  27.5 30.5]


#### Challenge 1: Which Location recorded the highest temperature on each day ?

In [28]:
# since there are five records for each station, therefore, each record represents a day.
# below are the numPy arrays of the recorded temperatures for each station.
Lagos
Abuja
Ibadan

# the code below is to find the highest temperature for each day.

for day in range (5):
    highest_temp = max(Lagos[day],Abuja[day],Ibadan[day])

    if highest_temp == Lagos[day]:
        location = "Lagos"

    elif highest_temp == Abuja[day]:
        location = "Abuja"

    else:
        location = "Ibadan"


    print ("Highest Temperature for Day",day + 1,":", location,"->", highest_temp)

Highest Temperature for Day 1 : Lagos -> 27.5
Highest Temperature for Day 2 : Lagos -> 29.0
Highest Temperature for Day 3 : Lagos -> 30.5
Highest Temperature for Day 4 : Abuja -> 30.0
Highest Temperature for Day 5 : Abuja -> 32.0


#### Challenge 2: Increase every Temperature record by 1

In [29]:
# the code below is to increase every temperature record for each station by 1 degree.
# to do this, we do not need to use a loop, as numpy array as an inbuild element-wise operation ability.
# therefore;

Lagos_plus1 = Lagos + 1
Abuja_plus1 = Abuja + 1
Ibadan_plus1 = Ibadan + 1

# the code below is to display the result of the increased temperature records for each station location
print (Lagos_plus1)
print (Abuja_plus1)
print (Ibadan_plus1)

[28.5 30.  31.5 29.  32. ]
[26.  29.  30.5 31.  33. ]
[27.5 29.5 30.  28.5 31.5]


#### Challenge 3: Compare the Temperatures of Lagos and Abuja

In [30]:
# the code below is to compare the temperatures of Lagos and Abuja Station
for day in range (5):
    if Lagos[day] > Abuja[day]:
        print ("Day", day+1, ": Lagos was Hotter")

    elif Abuja[day] > Lagos[day]:
        print ("Day", day+1,": Abuja was Hotter")

    else:
        print ("Day", day+1, ": the Temperature of both locations were the same")

Day 1 : Lagos was Hotter
Day 2 : Lagos was Hotter
Day 3 : Lagos was Hotter
Day 4 : Abuja was Hotter
Day 5 : Abuja was Hotter


#### Challenge 4: Why NumPy is Increasingly useful as the numerical data grows

In [31]:
# the code below is to display the explanation for the challenge 4 above
print(f"""
NumPy is becomes increasingly useful as the numeric data grows because, 
numPy arrays operate on one common data type, which enables the execution process
to be efficient and seamless. And also NumPy ability to perform element-wise operations
also makes the execution time faster, compared to using just python list.
""")


NumPy is becomes increasingly useful as the numeric data grows because, 
numPy arrays operate on one common data type, which enables the execution process
to be efficient and seamless. And also NumPy ability to perform element-wise operations
also makes the execution time faster, compared to using just python list.



### --------------------------------------------------------------------------------------------------
##### My Findings:
1: converting a numeric dataset to an array makes its easier to perform mathematical operations
   on the dataset without writing many lines of code.

2: In the comaprison of the Temperature records of the station locations of Lagos and Abuja, I discovered
   that on three days out of Five days, the Temperature records of Lagos was higher than that of Abuja.

3: Without Initially Importing NumPy, before starting any conversion of python lists to Arrays operations, jupyter notebook
   would display an error that it doesn't recognise the short form "np" that was used to represent NumPy.

### Bonus Challenge

In [34]:
# the code below is to test the bonus challenge output to see if it matches my earlier personal prediction of its results

# my predictions:
# print (x+y): would give the output [3,7,11]
# print (x-y): would give the output [1,1,1]
# print (x*y): would give the output [2,12,30]

x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print(x + y)
print(x - y)
print(x * y)


[ 3  7 11]
[1 1 1]
[ 2 12 30]


from the result displayes above, its safe to say my predictions were correct.

Thank You SmartBizCrux Technologies Team!